Reorganize, tests, shlog dep

diff --git a/shrender b/shrender
--- a/shrender
+++ b/shrender
@@ -5,36 +5,49 @@
 ## The render method is determined by the file extension, see 
 ## [RENDER STYLES](#render-styles) for a list of render methods
 
-## Runs on **first** pass
+SHRENDERSHARE="$(dirname "$0")"
 
-typeset -A EXT_TO_RENDER_FUNC
-export EXT_TO_RENDER_FUNC=()
-typeset -A EXT_TO_RENDER_PREFIX
-export EXT_TO_RENDER_PREFIX=()
-typeset -a SHRENDER_PATH
-export SHRENDER_PATH=()
-SHRENDER_PATH+=("$PWD")
+# logging
+export PATH="$PATH:$SHRENDERSHARE/deps/shlog"
+source "$(which shlog)"
+
+# Extension to XY mappings
+declare -Agx EXT_TO_RENDER_FUNC=(
+    [md]="cat"
+    [markdown]="cat"
+    [ronn]="cat"
+    [txt]="cat"
+    [jade]="jade"
+    [pug]="jade"
+)
+typeset -axg SHRENDER_PATH=("$PWD")
+
+source "$SHRENDERSHARE/shrender-jade"
+source "$SHRENDERSHARE/shrender-prefix"
 
 set -e
 
-_debug() {
-    echo -e "**DEBUG** : $*" >&2
+usage () {
+    echo "Usage: shrender [opts...] <file-to-render>...
+
+    Options:
+
+        -f --func RENDERFUNC    Use this render func
+        "
 }
 
-_error() {
-    echo -e "**ERROR**: $*" >&2
-    exit 1
+shrender-cat() {
+    cat "$1"
 }
 
-load_profile() {
-    for profile in "$PWD/shrender.profile" "/etc/default/shrender";do
-        if [[ -e "$profile" ]];then
-            source "$profile"
-        fi
+shrender-load-profile () {
+    for profile in "$SHRENDERSHARE/shrender.profile" "/etc/default/shrender" "$PWD/.shrenderrc";do
+        if [[ -e "$profile" ]];then source "$profile";fi
     done
+    return
 }
 
-resolve_file() {
+shrender-resolve-file() {
     local f=$1
     for dir in "${SHRENDER_PATH[@]}";do
         fabs="$dir/$f"
@@ -43,81 +56,67 @@ resolve_file() {
             return
         fi
     done
-    _error "No file found in includes: $renderfile"
-    return 1
+    shlog -l error -x 2 "No file found in includes: $renderfile"
 }
 
-render_func_for_file() {
+shrender-function-for-extension() {
     local f="$1"
     local ext=$(basename "$f"|sed 's/.*\.//')
-    _debug 1 "RENDER: Detecting render function by extension '$ext'"
+    shlog -l debug "Detecting render function by extension '$ext'"
     local renderfunc="${EXT_TO_RENDER_FUNC[$ext]}"
     if [[ -z "$renderfunc" ]];then
-        _debug 1 "RENDER: Fall back to 'prefix' render function"
+        shlog -l debug "RENDER: Fall back to 'prefix' render function"
         renderfunc='prefix'
     fi
     echo "$renderfunc"
 }
 
-render() {
-    local renderfile="${!#}"
-    for renderfile in "$@";do
-        if [[ -z "$renderfunc" ]];then
-            renderfunc="$(render_func_for_file "$renderfile")"
-        fi
-        if ! declare -f "_render_$renderfunc" >/dev/null;then
-            _error "Undefined render function '$renderfunc'."
-        fi
-        # _render_prefix
-        # _render_jade
-        local renderfile_abs=$(resolve_file "$renderfile")
-        _debug 1 "RENDER: Rendering $renderfile_abs"
-        _debug 0 "_render_$renderfunc '$*'"
-        "_render_$renderfunc" "$renderfile_abs"
-        if (( $? > 0 ));then
-            _error "Rendering failed: $output"
-        fi
-    done
-}
-
-_render_prefix() {
-    local prefix
-    local renderfile="${!#}"
-    local ext=${renderfile##*.}
-    _debug 1 "RENDER: Derive render prefix from extension '$ext'"
-    local prefix="${EXT_TO_RENDER_PREFIX[$ext]}"
+shrender() {
+    local renderfile renderfunc renderfile_abs
+    #man: ## OPTIONS
     while [[ "$1" = -* ]];do
         case "$1" in
-            -p|--prefix) prefix="$2"; shift ;;
-            *) _error "Unknown option '$1' to _render_prefix" ;;
+            #help:|-f,--func FUNCTION|Render function
+            -f|--func*) renderfunc="$2"; shift ;;
+            #help:|-p,--path PATH|Add path to shrenders search path
+            -p|--path) SHRENDER_PATH+=("$2"); shift ;;
+            *) break ;;
         esac
         shift
     done
-    if [[ -z "$prefix" ]];then
-        _debug 0 "Cannot derive render prefix from '$ext'."
-        _debug 0 "Falling back to renderprefix='##'."
-        _debug 0 "Define EXT_TO_RENDER_PREFIX[$ext]='...' to override.\n"
-        prefix='##'
-    fi
-    awk '{gsub("__CURLINE__",NR,$0);print}' "$1" \
-        | grep "^\s*$prefix" \
-        | sed "s/^\s*$prefix\s\?//"
+    [[ -z "$1" ]] && { usage; exit; }
+    shrender-load-profile 
+
+    for renderfile in "$@";do
+        renderfile_abs=$(shrender-resolve-file "$renderfile")
+        if (( $? > 0 ));then
+            shlog -l error -x $? "Failed to resolve '$renderfile'"
+        fi
+        if [[ -z "$renderfunc" ]];then
+            renderfunc="$(shrender-function-for-extension "$renderfile")"
+        fi
+        if ! declare -f "shrender-$renderfunc" >/dev/null;then
+            shlog -l error -x 7 "No such render function '$renderfunc'."
+        fi
+        shlog -l debug "Rendering $renderfile_abs"
+        shlog -l info "shrender-$renderfunc '$renderfile_abs'"
+        tempfile=$(mktemp --tmpdir "shrender.XXXXX.$(basename "$renderfile"|sed 's/.*\.//')")
+        # shellcheck disable=2064
+        trap "rm $tempfile" EXIT INT TERM
+        awk "{
+            gsub(\"__CURLINE__\",NR,\$0);
+            gsub(\"__CURFILE__\",\"$renderfile\",\$0);
+            print
+        }" < "$renderfile_abs" > "$tempfile"
+        "shrender-$renderfunc" "$tempfile"
+        if (( $? > 0 ));then
+            shlog -l error -x 7 "Rendering failed."
+        fi
+    done
 }
 
-_render_jade() {
-    local renderfile="${!#}"
-    # shellcheck disable=2094
-    jade -p "$renderfile" -P < "$renderfile" |sed -n '2,$p'
-}
-
-#man: ## OPTIONS
-while [[ "$1" = -* ]];do
-    case "$1" in
-        #help:|-f,--func FUNCTION|Render function
-        -f|--func*) renderfunc="$2"; shift ;;
-        *) break ;;
-    esac
-    shift
-done
-load_profile
-render "$@"
+if [[ "${BASH_SOURCE[0]}" = "$0" ]];then
+    shrender "$@"
+else
+    export -f shrender
+fi
